# Site settings
title: CodingCrush
email: codingcrush@163.com
copyright_name: TinyBlog-jekyll
description: CodingCrush's blog
baseurl: ""
url: "http://codingcrush.me"
github_username: CodingCrush
zhihu_username :
weibo_id: 2303345023
disqus_shortname:
duoshuo_shortname: codingcrush
github_repository: TinyBlog-jekyll

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
timezone: Asia/Shanghai