# Site settings
title: admin
email: admin@163.com
copyright_name: TinyBlog-jekyll
description: admin's blog
baseurl: ""
url: "http://admin.me"
github_username: admin
zhihu_username :
weibo_id: 
disqus_shortname:
duoshuo_shortname: admin
github_repository: TinyBlog-jekyll

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
timezone: Asia/Shanghai
